2025-06-19 01:25:32,920 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/routes/admin.py", line 266, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/routes/admin.py", line 479, in feedback
    return render_template('view_feedback.html', feedbacks=feedbacks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grove/GitHub/iApplications/iSaksham/app/templates/view_feedback.html", line 1, in top-level template code
    {%extends 'base.html'%}
  File "/home/grove/GitHub/iApplications/iSaksham/app/templates/base.html", line 232, in top-level template code
    {% block content %}
  File "/home/grove/GitHub/iApplications/iSaksham/app/templates/view_feedback.html", line 222, in block 'content'
    data-date="{{ feedback.created_at.strftime('%Y-%m-%d %H:%M:%S') }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'strftime'
2025-06-19 01:25:32,937 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/view_feedback
2025-06-19 01:25:32,941 [ERROR] in __init__: Payload: N/A
2025-06-19 01:26:18,385 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/routes/admin.py", line 266, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/routes/admin.py", line 479, in feedback
    return render_template('view_feedback.html', feedbacks=feedbacks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grove/GitHub/iApplications/iSaksham/app/templates/view_feedback.html", line 1, in top-level template code
    {%extends 'base.html'%}
  File "/home/grove/GitHub/iApplications/iSaksham/app/templates/base.html", line 232, in top-level template code
    {% block content %}
  File "/home/grove/GitHub/iApplications/iSaksham/app/templates/view_feedback.html", line 222, in block 'content'
    data-date="{{ feedback.created_at.strftime('%Y-%m-%d %H:%M:%S') }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'strftime'
2025-06-19 01:26:18,397 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/view_feedback
2025-06-19 01:26:18,402 [ERROR] in __init__: Payload: N/A
2025-06-19 01:38:25,606 [ERROR] in __init__: Unhandled Exception
Traceback (most recent call last):
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/routes/admin.py", line 266, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/grove/GitHub/iApplications/iSaksham/app/routes/admin.py", line 479, in feedback
    return render_template('view_feedback.html', feedbacks=feedbacks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grove/GitHub/iApplications/iSaksham/app/templates/view_feedback.html", line 1, in top-level template code
    {%extends 'base.html'%}
  File "/home/grove/GitHub/iApplications/iSaksham/app/templates/base.html", line 103, in top-level template code
    <a class="dropdown-item" href="{{url_for('admin.view_feedback')}}">View Feedbacks</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/flask/app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grove/miniconda3/envs/flask/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'admin.view_feedback'. Did you mean 'admin.feedback' instead?
2025-06-19 01:38:25,620 [ERROR] in __init__: URL: http://127.0.0.1:8080/isaksham/view_feedback
2025-06-19 01:38:25,624 [ERROR] in __init__: Payload: N/A
